name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2026-03-13"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "6ad4b61c-d094-456f-872f-fc27caf5de03"
